// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAof0OEI4i7dN1NeFvD9YTVL2fXpcPAJjU',
    appId: '1:493854551470:web:876963a4b2303021656c3f',
    messagingSenderId: '493854551470',
    projectId: 'yemekolikapp',
    authDomain: 'yemekolikapp.firebaseapp.com',
    storageBucket: 'yemekolikapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw1NUBHSlAA9C_1ZdWoCQ3kIIi6vLKmmM',
    appId: '1:493854551470:android:4bce32bf61f59809656c3f',
    messagingSenderId: '493854551470',
    projectId: 'yemekolikapp',
    storageBucket: 'yemekolikapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-_adIociVtJs9plQSW2grexnkTBSTxRI',
    appId: '1:493854551470:ios:8b99be79933fffae656c3f',
    messagingSenderId: '493854551470',
    projectId: 'yemekolikapp',
    storageBucket: 'yemekolikapp.firebasestorage.app',
    iosBundleId: 'com.example.yemekolikFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-_adIociVtJs9plQSW2grexnkTBSTxRI',
    appId: '1:493854551470:ios:8b99be79933fffae656c3f',
    messagingSenderId: '493854551470',
    projectId: 'yemekolikapp',
    storageBucket: 'yemekolikapp.firebasestorage.app',
    iosBundleId: 'com.example.yemekolikFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAof0OEI4i7dN1NeFvD9YTVL2fXpcPAJjU',
    appId: '1:493854551470:web:0f739b824095b0ab656c3f',
    messagingSenderId: '493854551470',
    projectId: 'yemekolikapp',
    authDomain: 'yemekolikapp.firebaseapp.com',
    storageBucket: 'yemekolikapp.firebasestorage.app',
  );
}
